# Numpy tutorial

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print("numpy array, a[0] = {}".format(a[0]))
print("numpy array, a[1:3] = {}".format(a[1:3]))
for x in a:
    print("numpy array element: ", x)

numpy array, a[0] = 1
numpy array, a[1:3] = [2 3]
numpy array element:  1
numpy array element:  2
numpy array element:  3
numpy array element:  4
numpy array element:  5


In [3]:
l = [1,2,3,4,5]
print("list, l[0] = {}".format(l[0]))
print("list, l[1:3] = {}".format(l[1:3]))
for x in l:
    print("list element: ", x)

list, l[0] = 1
list, l[1:3] = [2, 3]
list element:  1
list element:  2
list element:  3
list element:  4
list element:  5


In [4]:
a = np.array([[1,2,3], [4,5,6]])
print("mean value over all elements: ", a.mean())
print("mean value for each row: ", a.mean(axis=1))
print("mean value for each column: ", a.mean(axis=0))

mean value over all elements:  3.5
mean value for each row:  [2. 5.]
mean value for each column:  [2.5 3.5 4.5]


In [5]:
l = [[1,2,3], [4,5,6]]
print("mean value over all elements: ", (sum(l[0])+sum(l[1]))/6)

mean value over all elements:  3.5


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a+b = {}".format(a+b))
print("a*b = {}".format(a*b))
print("a*3 = {}".format(a*3))
print("a&b = {}".format(a&b))
print("a>b = {}".format(a>b))

a+b = [5 7 9]
a*b = [ 4 10 18]
a*3 = [3 6 9]
a&b = [0 0 2]
a>b = [False False False]


In [7]:
# using index arrays
a = np.array([1, 2, 3, 4])
b = np.array([True, True, False, False])
print(a[b])
print(a[a>2])
# creating the index array using vectorized operations
b = a >2
print(b)
# array of booleans can be used with numpy functions
print(b.mean())


[1 2]
[3 4]
[False False  True  True]
0.5


In [8]:
# case 1: both a and b refer to the same array
a = np.array([1,2,3])
b = a
a += 1
print(b)

[2 3 4]


In [9]:
# case 2: both a and b refer to the same array, 
# but later a is reassigned, which creates a new array. 
# Then a refers to a new array while b refers 
# to the original array
a = np.array([1,2,3])
b = a
a = a + 1
print(b)


[1 2 3]


In [10]:
# try numpy array
a = np.array([1,2,3,4])
# take a slice, numpy doesn't create a new array.
Slice = a[:3]
Slice[0] = 10
print(a)


[10  2  3  4]


In [11]:
a = [1,2,3,4]
Slice = a[:3]
Slice[0] = 10
print(a)

[1, 2, 3, 4]


In [12]:
arr = np.array([[1,2,3],
                [4,5,6], 
                [7,8,9]])
print(arr)
print(arr[1,1])
print(arr[1,:]) #This will return all elements of 1st row in the form of array
print(arr[1:3,1:3]) # return multiple rows and columns 
print(arr[1][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[4 5 6]
[[5 6]
 [8 9]]
6


In [13]:
a = np.arange(12)**2  # the first 12 square numbers
i = np.array([1, 1, 3, 8, 5])  # an array of indices
print(a[i])  # the elements of `a` at the positions `i`
j = np.array([[3, 4], [9, 7]])  # a bidimensional array of indices
print(a[j])  # the same shape as `j`

[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]


In [14]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a, b))
d = np.stack((a,b))
e = d[0:3, :]
print("c = {}".format(c))
print("d = {}".format(d))
print("e = {}".format(e))

c = [1 2 3 4 5 6 7 8]
d = [[1 2 3 4]
 [5 6 7 8]]
e = [[1 2 3 4]
 [5 6 7 8]]


In [16]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
print(array_example.ndim)
print(array_example.size)
print(array_example.shape)

3
24
(3, 2, 4)


In [17]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [18]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2, 3))
print(arr.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


# Pandas

In [19]:
import pandas as pd

In [20]:
series1 = pd.Series(['a','b','c','d'])
series2 = pd.Series(['e','f','g','h'])
print("series1[0] = \n", series1[0])
print("series1[1:3] = \n", series1[1:3])
print("series1 + series2 = \n", series1+series2)

series1[0] = 
 a
series1[1:3] = 
 1    b
2    c
dtype: object
series1 + series2 = 
 0    ae
1    bf
2    cg
3    dh
dtype: object


In [21]:
series = pd.Series(['aa','bb','cc','dd'], index=['a','b','c','d'])
print("series.index = ", series.index)
print("access element by index, series.loc['a'] = ", series.loc['a'])
print("access element by position, series[2] = ", series[2])
print("access element by position, series.iloc[2] = ", series.iloc[2])

series.index =  Index(['a', 'b', 'c', 'd'], dtype='object')
access element by index, series.loc['a'] =  aa
access element by position, series[2] =  cc
access element by position, series.iloc[2] =  cc


In [22]:
# create a pandas 2d dataframe
df = pd.DataFrame(np.arange(6).reshape(2,3), index=['a','b'], columns=['c1','c2','c3'])
print('df.shape = ', df.shape)
print('df.index = ', df.index)
print('df = \n',df)

df.shape =  (2, 3)
df.index =  Index(['a', 'b'], dtype='object')
df = 
    c1  c2  c3
a   0   1   2
b   3   4   5


In [23]:
# convert a dictionary to dataframe, 
# the key is converted as column names.
dic = {'a':[1,2,3], 'b':[4,5,6]}
df = pd.DataFrame(dic, index=['x', 'y', 'z'])
print('df = \n', df)
print('df.mean = \n', df.mean())
print('df.values.mean = ',df.values.mean())

df = 
    a  b
x  1  4
y  2  5
z  3  6
df.mean = 
 a    2.0
b    5.0
dtype: float64
df.values.mean =  3.5


In [24]:
# convert a 2D numpy array or list of lists to pandas dataframe
df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
print(df_2)

   A  B  C
0  0  1  2
1  3  4  5


In [25]:
dic = {'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]}
df = pd.DataFrame(dic, index=['x', 'y', 'z'])
print("Access elements by row, df.iloc[0] = ", df.iloc[0]) # access elements, first row
print("Each row in DataFrame is a Pandas Series: ", type(df.iloc[0])) # pandas series
print("Access elements by index, df.loc['x'] = ", df.loc['x']) # row whose index is 'x'
print("Access elements by column, df['a'] = ", df['a']) # column whose column name is 'a'
print("Access single element df.iloc[1, 2] = ", df.iloc[1, 2]) # # access 2nd row, 3rd column
print("Access multiple rows df.iloc[1:3] = ", df.iloc[1:3]) # access multiple rows
print("Access multiple columns, df[['a', 'b']]", df[['a', 'b']]) # access multiple columns

Access elements by row, df.iloc[0] =  a    1
b    4
c    7
Name: x, dtype: int64
Each row in DataFrame is a Pandas Series:  <class 'pandas.core.series.Series'>
Access elements by index, df.loc['x'] =  a    1
b    4
c    7
Name: x, dtype: int64
Access elements by column, df['a'] =  x    1
y    2
z    3
Name: a, dtype: int64
Access single element df.iloc[1, 2] =  8
Access multiple rows df.iloc[1:3] =     a  b  c
y  2  5  8
z  3  6  9
Access multiple columns, df[['a', 'b']]    a  b
x  1  4
y  2  5
z  3  6


In [26]:
dic = {'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]}
df = pd.DataFrame(dic, index=['x', 'y', 'z'])
df.to_csv("test.csv", index=False) # write DataFrame to test.csv
df2 = pd.read_csv("test.csv")      # read DataFrame from disk
print(df2)

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9
